/**
 * Copyright (C) 2011 Darien Hager
 *
 * This code is part of the "PackBSP" project, and is licensed under
 * a Creative Commons Attribution-ShareAlike 3.0 Unported License. For
 * either a summary of conditions or the full legal text, please visit:
 *
 * http://creativecommons.org/licenses/by-sa/3.0/
 *
 * Permissions beyond the scope of this license may be available
 * at http://technofovea.com/ .
 */
package com.technofovea.packbsp.gui2.jung;

import com.technofovea.packbsp.GraphListener;
import com.technofovea.packbsp.crawling.DependencyGraph;
import com.technofovea.packbsp.crawling.Edge;
import com.technofovea.packbsp.crawling.Node;
import edu.uci.ics.jung.algorithms.layout.ISOMLayout;
import edu.uci.ics.jung.algorithms.layout.Layout;
import java.awt.Dimension;
import java.lang.reflect.InvocationTargetException;
import javax.swing.SwingUtilities;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author Darien Hager
 */
public class GraphPanel extends javax.swing.JPanel implements GraphListener {

    private static final Logger logger = LoggerFactory.getLogger(GraphPanel.class);
    DependencyVisualizer vis = null;

    /** Creates new form GraphPanel */
    public GraphPanel() {
        initComponents();
    }

    public void graphCreated(DependencyGraph graph) {
        final Layout<Node, Edge> layout = new ISOMLayout<Node, Edge>(graph);    
        final DependencyVisualizer dv = new DependencyVisualizer(layout,new Dimension(400,400));
        final GraphPanel panel = this;
        synchronized(this){
            try{
            SwingUtilities.invokeAndWait(new Runnable() {
                public void run() {
                    panel.removeAll();
                    panel.add(dv);
                    dv.setVisible(true);
                }
            });
            vis = dv;
            }catch(InterruptedException e){
                logger.error("Error refreshing graph",e);
            }catch(InvocationTargetException e){
                logger.error("Error refreshing graph",e);
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
